# Generated by Django 3.1.1 on 2020-09-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200924_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precios_venta',
            old_name='id_Lugar_venta',
            new_name='id_lugar',
        ),
    ]
